# -*- coding: utf-8 -*-
"""JSON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19EF1-kuX3BrDDN1jvzs_Zy5PYyTgH4Ry
"""

pip install gradio json5 jsonschema pydantic python-dotenv

pip install gradio json5 jsonschema pydantic python-dotenv

import gradio as gr
import json
import re
from jsonschema import validate, ValidationError

history_log = []

# -----------------------------
# TYPE INFERENCE
# -----------------------------
def infer_type(value):

    value = value.strip()

    if value.lower() in ["true","yes","on"]:
        return True

    if value.lower() in ["false","no","off"]:
        return False

    if value.lower() in ["null","none","nil","n/a"]:
        return None

    if re.match(r"^-?\d+$",value):
        return int(value)

    if re.match(r"^-?\d+\.\d+$",value):
        return float(value)

    try:
        return json.loads(value)
    except:
        return value


# -----------------------------
# KEY VALUE PARSER
# -----------------------------
def parse_key_value(text):

    data={}

    for line in text.split("\n"):

        if ":" not in line:
            continue

        k,v=line.split(":",1)

        data[k.strip()]=infer_type(v)

    return data


# -----------------------------
# CASE CONVERSION
# -----------------------------
def snake_case(key):

    words=re.findall(r"[A-Za-z0-9]+",key)
    return "_".join(w.lower() for w in words)


def camel_case(key):

    words=re.findall(r"[A-Za-z0-9]+",key)

    return words[0].lower()+"".join(w.title() for w in words[1:])


def kebab_case(key):

    words=re.findall(r"[A-Za-z0-9]+",key)

    return "-".join(w.lower() for w in words)


def pascal_case(key):

    words=re.findall(r"[A-Za-z0-9]+",key)

    return "".join(w.title() for w in words)


def convert_case(data,style):

    new={}

    for k,v in data.items():

        if style=="snake_case":
            new_key=snake_case(k)

        elif style=="camelCase":
            new_key=camel_case(k)

        elif style=="kebab-case":
            new_key=kebab_case(k)

        elif style=="PascalCase":
            new_key=pascal_case(k)

        else:
            new_key=k

        new[new_key]=v

    return new


# -----------------------------
# REMOVE NULL
# -----------------------------
def remove_null(data):

    return {k:v for k,v in data.items() if v!=None}


# -----------------------------
# FLATTEN JSON
# -----------------------------
def flatten_json(y,parent=""):

    out={}

    for k,v in y.items():

        new_key=f"{parent}.{k}" if parent else k

        if isinstance(v,dict):
            out.update(flatten_json(v,new_key))

        else:
            out[new_key]=v

    return out


# -----------------------------
# UNFLATTEN JSON
# -----------------------------
def unflatten_json(data):

    result={}

    for k,v in data.items():

        keys=k.split(".")

        d=result

        for key in keys[:-1]:

            d=d.setdefault(key,{})

        d[keys[-1]]=v

    return result


# -----------------------------
# MERGE JSON
# -----------------------------
def merge_json(j1,j2,j3):

    result={}

    for j in [j1,j2,j3]:

        if j.strip():

            result.update(json.loads(j))

    return json.dumps(result,indent=2)


# -----------------------------
# MAIN REFINER
# -----------------------------
def refine_json(text,case_style,remove_nulls,flatten):

    data=parse_key_value(text)

    data=convert_case(data,case_style)

    if remove_nulls:
        data=remove_null(data)

    if flatten:
        data=flatten_json(data)

    output=json.dumps(data,indent=2)

    history_log.append(output)

    return output


# -----------------------------
# VALIDATION
# -----------------------------
def validate_json(json_text,schema_text):

    try:

        data=json.loads(json_text)

        schema=json.loads(schema_text)

        validate(data,schema)

        return "✅ JSON is valid"

    except ValidationError as e:

        return f"❌ {e.message}"

    except Exception as e:

        return str(e)


# -----------------------------
# HISTORY
# -----------------------------
def show_history():

    return "\n\n".join(history_log)


def clear_history():

    history_log.clear()

    return ""


# -----------------------------
# CUSTOM CSS
# -----------------------------
css="""
body{background:#0f172a}
.gradio-container{background:#0f172a;color:white}
textarea{background:#1e293b;color:white}
"""

# -----------------------------
# UI
# -----------------------------
with gr.Blocks(css=css,title="JSON Refiner Advanced Edition") as app:

    gr.Markdown("# JSON Refiner Advanced Edition")
    gr.Markdown("Professional JSON Processing Tool")

    with gr.Tabs():

        # CORE
        with gr.Tab("Core Refining"):

            inp=gr.Textbox(lines=10,label="Input Format")

            case=gr.Radio(
                ["snake_case","camelCase","kebab-case","PascalCase"],
                value="snake_case",
                label="Key Case Style"
            )

            remove=gr.Checkbox(label="Remove Nulls")

            flat=gr.Checkbox(label="Flatten")

            btn=gr.Button("Refine JSON")

            out=gr.Code(label="Refined JSON")

            btn.click(refine_json,[inp,case,remove,flat],out)

        # VALIDATION
        with gr.Tab("Validation"):

            j=gr.Textbox(label="JSON")

            s=gr.Textbox(label="Schema")

            vbtn=gr.Button("Validate")

            vout=gr.Textbox()

            vbtn.click(validate_json,[j,s],vout)

        # CASE CONVERSION
        with gr.Tab("Case Conversion"):

            j2=gr.Textbox(label="Input JSON")

            style=gr.Radio(["snake_case","camelCase","kebab-case","PascalCase"])

            cbtn=gr.Button("Convert")

            cout=gr.Code()

            def convert_ui(j,style):

                return json.dumps(
                    convert_case(json.loads(j),style),
                    indent=2
                )

            cbtn.click(convert_ui,[j2,style],cout)

        # MERGE
        with gr.Tab("Merge JSON"):

            j1=gr.Textbox(label="JSON 1")
            j2=gr.Textbox(label="JSON 2")
            j3=gr.Textbox(label="JSON 3")

            mbtn=gr.Button("Merge")

            mout=gr.Code()

            mbtn.click(merge_json,[j1,j2,j3],mout)

        # FLATTEN
        with gr.Tab("Flatten/Unflatten"):

            fj=gr.Textbox(label="JSON")

            fbtn=gr.Button("Flatten")

            fout=gr.Code()

            def flat_ui(j):

                return json.dumps(flatten_json(json.loads(j)),indent=2)

            fbtn.click(flat_ui,fj,fout)

        # HISTORY
        with gr.Tab("History"):

            hbtn=gr.Button("Download History")

            clear=gr.Button("Clear History")

            hout=gr.Textbox(lines=15)

            hbtn.click(show_history,None,hout)

            clear.click(clear_history,None,hout)

        # GUIDE
        with gr.Tab("Guide"):

            gr.Markdown("""
### JSON Refiner Guide

Input format example:

name: John
age: 28
active: true
balance: 1500.50

Type inference:
- true / false → Boolean
- numbers → int/float
- null → Null
- arrays → JSON list
            """)

app.launch()